### PR TITLE
Port to Bevy 0.11

### PR DESCRIPTION
**Pull request by johanhelsing**

### CODE REVIEW

**Comment by KirmesBude** [comment]
Thanks

**Comment by johanhelsing** [comment]
No problem :) could you do a crates.io release as well, when you have the time? 🙏

**Comment by KirmesBude** [comment]
Oh, yeah. Just published the new version.
Sorry, have been busy with Baldurs Gate :D

**Comment by johanhelsing** [comment]
Haha, totally relatable :D Have fun :)

**Pull request merged**
